### ISSUE TITLE
Create a banner for our webpage

### ISSUE THREAD

**Issue by dPliakos** [ieee-ihuthess/managing_the_branch#22]
We need a new banner for our webpage. Right now we have this
![IEEEATEITHSBLogo](https://user-images.githubusercontent.com/17273872/64567856-e47a0080-d361-11e9-8383-2561830ad20e.png)

We need something more IHUish

**Comment by dpliakos** [comment]
The old web page will not survive the transition to ihu.  Should we drop ti @joj0s?

**Comment by joj0s** [comment]
Big yes vote
